spring.application.name=backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/insurai?useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:insurai_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:insurai123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=${JWT_SECRET:InsurAI_JWT_SECRET_2025@secure}

spring.datasource.hikari.maximum-pool-size=3

server.port=8080
